### ISSUE TITLE
slurm mail Err: cancelled jobs that are pending

### ISSUE THREAD

**Issue by rzegson** [neilmunday/slurm-mail#50] opened 2022-08-25 16:28 UTC
**Versions**

OS version:Centos7
Slurm version: 22.05.2
Slurm Mail version: 3.1

**Describe the bug**
Our site recently upgraded from Slurm 21.08.8 to 22.05.2 and noticed multiple errors within slurm-send-mail.py when users cancel pending jobs. We were able to produce the error with version 3.1 and 3.5 of Slurm Mail.

A clear and concise description of what the bug is and how it to produce it.

Have a user submit a job with mail-type=ALL. While job is pending, cancel the job and check slurm-send-mail.py logs. 

We noticed pre 22.05.2, sacct Start would show 'Unknown' for a cancelled job. Using 22.05.2 sacct Start shows 'None' for a cancelled job.

**Logs**

Include any log snippets here - please used code tags.

The error we have received within slurm-send-mail.py:

2022/08/25 11:10:02:ERROR: Failed to process: /var/spool/slurm-mail/307964_1661442566.5445702.mail
2022/08/25 11:10:02:ERROR: invalid literal for int() with base 10: 'None'
Traceback (most recent call last):
  File "/opt/slurm-mail/bin/slurm-send-mail.py", line 811, in <module>
    process_spool_file(f)
  File "/opt/slurm-mail/bin/slurm-send-mail.py", line 449, in process_spool_file
    job.start_ts = sacct_dict['Start']
  File "/opt/slurm-mail/bin/slurm-send-mail.py", line 171, in start_ts
    self.__start_ts = int(ts)
ValueError: invalid literal for int() with base 10: 'None'

We upgraded on 8/8. Using sacct, we compared a pending job that a user cancelled with version 21.08.8 to the same pending job cancellation with 22.05.2

21.08.8 

Submit    |                               Partition    |                   Start   |               End       |           State   |                JobID
2022-08-04T12:25:43 |            general     |         Unknown    |    2022-08-04T12:26:10  | CANCELLED    |        292735

22.05.2 

Submit   |                                 Partition           |            Start               |   End               |   State              |     JobID
2022-08-08T16:21:33          |    general            |  None        | 2022-08-08T16:24:46       | CANCELLED           |       299636

**Comment by neilmunday** [comment] 2022-08-25 23:12
Hi @rzegson,

Thanks for providing a detailed report of the bug.

You are correct, this [line](https://github.com/neilmunday/slurm-mail/blob/main/bin/slurm-send-mail.py#L466) is the cause:

```
if sacct_dict['Start'] != 'Unknown':
    job.start_ts = sacct_dict['Start']
```

I will work on a fix.

For now, if you change the above if statement in `slurm-send-mail.py` to:

```
if sacct_dict['Start'] != 'Unknown' and sacct_dict['Start'] != 'None' :
```

A better fix I think will be to test if the start field can be parsed to an int or not.

**Comment by rzegson** [comment] 2022-08-26 19:04
Thank you Neil! We really appreciate the work that you do.

**Comment by neilmunday** [comment] 2022-08-26 21:26
@rzegson thank you for you kind words :-)

I'll keep this issue open until I have committed a fix.

**Comment by neilmunday** [comment] 2022-08-26 21:55
Fixed by: https://github.com/neilmunday/slurm-mail/commit/52d7a900ea866387a205ae3fca4a674fa5bdbca2

**Closed by neilmunday** 2022-08-26 21:55 UTC
Labels: bug
