### ISSUE TITLE
Job completed, but email stating "did not run"

### ISSUE THREAD

**Issue by pddro-Vestas** [neilmunday/slurm-mail#103] opened 2023-12-12 22:16 UTC
**Versions**

OS version: Ubuntu 20.04 LTS
Slurm version: 23.02
Slurm Mail version: latest

**Describe the bug**

The job completes correctly, but the email states that job "did not run".
Example:
Emails Subject: 
Job cluster.10664: Ended

Email body:
Dear Pedro,
Your job 10664 did not run on cluster.

Also the Std out and Std err are not populated correctly and show as below:
Std out: ?
Std err:  ?

Thanks for your help.

**Comment by neilmunday** [comment] 2023-12-15 08:20
Hi,

Are you able to supply the output from the following command please to help debug the issue:

```
sacct -j 10664 --fields=Start,End,State,NNodes,Elapsed,ExitCode,TimeLimit,TimelimitRaw
```

**Comment by pddro-Vestas** [comment] 2023-12-15 08:56
Hi,

Thanks for the reply, See below:
sacct -j 10664 --fields=Start,End,State,NNodes,Elapsed,ExitCode,TimeLimit,TimelimitRaw
              Start                 End      State   NNodes    Elapsed ExitCode  Timelimit TimelimitR
------------------- ------------------- ---------- -------- ---------- -------- ---------- ----------
2023-12-12T21:52:11 2023-12-12T22:03:46  COMPLETED        1   00:11:35      0:0   02:00:00        120
2023-12-12T21:52:11 2023-12-12T22:03:46  COMPLETED        1   00:11:35      0:0

**Comment by neilmunday** [comment] 2023-12-15 19:28
Thank you for the output. I can't see at the moment how this has happened. Has the issue happened more than once?

Please can you edit `/etc/slurm-mail/slurm-mail.conf` and set `verbose = true` in the `[slurm-spool-mail]` and `[slurm-send-mail]` sections of the file.

Then when the issue happens again, please can you share with me the sections of `/var/log/slurm-mail/slurm-send-mail.log` and `/var/log/slurm-mail/slurm-spool-mail.log` for around the time the job started and ended?

This should then capture the output of `sacct` at the time the job ended and also the content of the spool file created.

**Comment by neilmunday** [comment] 2023-12-18 21:36
The issue appears to be caused by the `TotalCPU` field returning `00:00:00` for the job which means it used no CPU. On my tests with a 1 minute job created using `sleep 60` this field reports some microseconds usage at least.

As it stands Slurm-Mail is using the `TotalCPU` field to determine whether a job actually ran or not. Are the jobs you are running executing anything?

**Comment by pddro-Vestas** [comment] 2023-12-18 22:02
Thanks for the reply. Yes, this test script copied some files, printed some output and exited.

See below output of sacct . CPUTime is showing some data.

```
sacct -j 12675 --fields=Start,End,State,NNodes,Elapsed,ExitCode,TimeLimit,TimelimitRaw,CPU,TotalCPU
              Start                 End      State   NNodes    Elapsed ExitCode  Timelimit TimelimitR    CPUTime   TotalCPU
------------------- ------------------- ---------- -------- ---------- -------- ---------- ---------- ---------- ----------
2023-12-18T08:51:32 2023-12-18T08:52:32  COMPLETED        1   00:01:00      0:0 3-00:00:00       4320   00:04:00   00:00:00
2023-12-18T08:51:32 2023-12-18T08:52:32  COMPLETED        1   00:01:00      0:0                         00:04:00   00:00:00
```

**Comment by pddro-Vestas** [comment] 2023-12-19 22:14
Thanks for your help :)

**Comment by neilmunday** [comment] 2023-12-20 10:04
In branch [issue_103](https://github.com/neilmunday/slurm-mail/tree/issue_103) I have implemented a fix.

I would be interested to know if this fixes the issue for you.

To try out the fix you can download the modified [cli.py](https://raw.githubusercontent.com/neilmunday/slurm-mail/issue_103/src/slurmmail/cli.py) and [slurm.py](https://raw.githubusercontent.com/neilmunday/slurm-mail/issue_103/src/slurmmail/slurm.py) and then copy these files to your Slurm-Mail's installation directory.

**Comment by pddro-Vestas** [comment] 2023-12-21 18:52
Thanks a lot for the patched scripts . I have replaced the following:
- /usr/lib/python3/dist-packages/slurmmail/slurm.py
- /usr/lib/python3/dist-packages/slurmmail/cli.py

And now it works correctly! Also the Stdout and Stderr are correctly displayed! 

Thanks again for the quick solution.

**Comment by neilmunday** [comment] 2023-12-25 13:09
Glad to here the modifications worked for you. These will be included in the next release.

**Comment by neilmunday** [comment] 2023-12-25 13:32
Version 4.8 released.

**Closed by neilmunday** 2023-12-25 13:32 UTC
Labels: bug
